[package]
name = "papender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
clap = { version = "4.4.8", features = ["cargo"] }
config = "0.14.0"
anyhow = "1.0.82"
